schema = 3
result-type = "text"
perms-request = "always-allow"
description = "List all environment variables and their values."
command = "@BIN@/list"

[annotations]
read-only-hint = true
idempotent-hint = true
