// Code generated by tommy 0.4.5 (031c877); DO NOT EDIT.

package schema

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/moxy/internal/credentials"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type configServersHandle struct {
	node *cst.Node
}
type ConfigDocument struct {
	data    Config
	cstDoc  *document.Document
	model   *cst.Value
	servers []configServersHandle
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vEphemeral, _ok := model.Get("ephemeral"); _ok && _vEphemeral.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vEphemeral.Leaf); _xok {
			d.data.Ephemeral = &_x
			_vEphemeral.MarkConsumed()
		}
	}
	if _vProgressiveDisclosure, _ok := model.Get("progressive-disclosure"); _ok && _vProgressiveDisclosure.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vProgressiveDisclosure.Leaf); _xok {
			d.data.ProgressiveDisclosure = &_x
			_vProgressiveDisclosure.MarkConsumed()
		}
	}
	if _vBuiltinNative, _ok := model.Get("builtin-native"); _ok && _vBuiltinNative.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vBuiltinNative.Leaf); _xok {
			d.data.BuiltinNative = &_x
			_vBuiltinNative.MarkConsumed()
		}
	}
	if _vDisableMoxins, _ok := model.Get("disable-moxins"); _ok && _vDisableMoxins.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vDisableMoxins.Leaf); _xok {
			d.data.DisableMoxins = _x
			if d.data.DisableMoxins == nil {
				d.data.DisableMoxins = []string{}
			}
			_vDisableMoxins.MarkConsumed()
		}
	}
	if _vDisableServers, _ok := model.Get("disable-servers"); _ok && _vDisableServers.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vDisableServers.Leaf); _xok {
			d.data.DisableServers = _x
			if d.data.DisableServers == nil {
				d.data.DisableServers = []string{}
			}
			_vDisableServers.MarkConsumed()
		}
	}
	if _vCredentials, _ok := model.Get("credentials"); _ok && _vCredentials.Kind == cst.VTable {
		_vCredentials.MarkSeen()
		commandConfigVal := &credentials.CommandConfig{}
		if err := credentials.DecodeCommandConfigInto(commandConfigVal, _vCredentials); err != nil {
			return nil, fmt.Errorf("credentials: %w", err)
		}
		d.data.Credentials = commandConfigVal
	}
	if _vServers, _ok := model.Get("servers"); _ok && _vServers.Kind == cst.VArray {
		_vServers.MarkSeen()
		d.data.Servers = make([]ServerConfig, len(_vServers.Items))
		d.servers = make([]configServersHandle, len(_vServers.Items))
		for i := range _vServers.Items {
			_eServers := &_vServers.Items[i]
			_eServers.MarkSeen()
			d.servers[i] = configServersHandle{node: _eServers.Node}
			if _vServersName, _ok := _eServers.Get("name"); _ok && _vServersName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersName.Leaf); _xok {
					d.data.Servers[i].Name = _x
					_vServersName.MarkConsumed()
				}
			}
			if _vServersCommand, _ok := _eServers.Get("command"); _ok && _vServersCommand.Kind == cst.VLeaf {
				if _raw, _xok := cst.ExtractRaw(_vServersCommand.Leaf); _xok {
					if err := d.data.Servers[i].Command.UnmarshalTOML(_raw); err != nil {
						return nil, fmt.Errorf("command: %w", err)
					}
					_vServersCommand.MarkConsumed()
				}
			}
			if _vServersUrl, _ok := _eServers.Get("url"); _ok && _vServersUrl.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersUrl.Leaf); _xok {
					d.data.Servers[i].URL = _x
					_vServersUrl.MarkConsumed()
				}
			}
			if _vServersHeaders, _ok := _eServers.Get("headers"); _ok && _vServersHeaders.Kind == cst.VTable {
				_vServersHeaders.MarkSeen()
				d.data.Servers[i].Headers = make(map[string]string)
				for _iServersHeaders := range _vServersHeaders.Fields {
					_fServersHeaders := &_vServersHeaders.Fields[_iServersHeaders]
					if _fServersHeaders.Val.Kind == cst.VLeaf {
						if _s, _sok := cst.ExtractString(_fServersHeaders.Val.Leaf); _sok {
							d.data.Servers[i].Headers[_fServersHeaders.Key] = _s
							_fServersHeaders.Val.MarkConsumed()
						}
					}
				}
			}
			if _vServersHeadersHelper, _ok := _eServers.Get("headers-helper"); _ok && _vServersHeadersHelper.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersHeadersHelper.Leaf); _xok {
					d.data.Servers[i].HeadersHelper = &_x
					_vServersHeadersHelper.MarkConsumed()
				}
			}
			if _vServersOauth, _ok := _eServers.Get("oauth"); _ok && _vServersOauth.Kind == cst.VTable {
				_vServersOauth.MarkSeen()
				oAuthVal0 := &OAuthConfig{}
				if _vServersOauthClientId, _ok := _vServersOauth.Get("client-id"); _ok && _vServersOauthClientId.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vServersOauthClientId.Leaf); _xok {
						oAuthVal0.ClientID = _x
						_vServersOauthClientId.MarkConsumed()
					}
				}
				if _vServersOauthCallbackPort, _ok := _vServersOauth.Get("callback-port"); _ok && _vServersOauthCallbackPort.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vServersOauthCallbackPort.Leaf); _xok {
						oAuthVal0.CallbackPort = _x
						_vServersOauthCallbackPort.MarkConsumed()
					}
				}
				d.data.Servers[i].OAuth = oAuthVal0
			} else {
				oAuthVal0 := &OAuthConfig{}
				_foundServersOauth := false
				if _vClientId, _ok := _eServers.Get("client-id"); _ok && _vClientId.Kind == cst.VLeaf {
					_foundServersOauth = true
					if _x, _xok := cst.ExtractString(_vClientId.Leaf); _xok {
						oAuthVal0.ClientID = _x
						_vClientId.MarkConsumed()
					}
				}
				if _vCallbackPort, _ok := _eServers.Get("callback-port"); _ok && _vCallbackPort.Kind == cst.VLeaf {
					_foundServersOauth = true
					if _x, _xok := cst.ExtractInt(_vCallbackPort.Leaf); _xok {
						oAuthVal0.CallbackPort = _x
						_vCallbackPort.MarkConsumed()
					}
				}
				if _foundServersOauth {
					d.data.Servers[i].OAuth = oAuthVal0
				}
			}
			if _vServersAnnotations, _ok := _eServers.Get("annotations"); _ok && _vServersAnnotations.Kind == cst.VTable {
				_vServersAnnotations.MarkSeen()
				annotationsVal1 := &AnnotationFilter{}
				if _vServersAnnotationsReadOnlyHint, _ok := _vServersAnnotations.Get("readOnlyHint"); _ok && _vServersAnnotationsReadOnlyHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsReadOnlyHint.Leaf); _xok {
						annotationsVal1.ReadOnlyHint = &_x
						_vServersAnnotationsReadOnlyHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsDestructiveHint, _ok := _vServersAnnotations.Get("destructiveHint"); _ok && _vServersAnnotationsDestructiveHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsDestructiveHint.Leaf); _xok {
						annotationsVal1.DestructiveHint = &_x
						_vServersAnnotationsDestructiveHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsIdempotentHint, _ok := _vServersAnnotations.Get("idempotentHint"); _ok && _vServersAnnotationsIdempotentHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsIdempotentHint.Leaf); _xok {
						annotationsVal1.IdempotentHint = &_x
						_vServersAnnotationsIdempotentHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsOpenWorldHint, _ok := _vServersAnnotations.Get("openWorldHint"); _ok && _vServersAnnotationsOpenWorldHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsOpenWorldHint.Leaf); _xok {
						annotationsVal1.OpenWorldHint = &_x
						_vServersAnnotationsOpenWorldHint.MarkConsumed()
					}
				}
				d.data.Servers[i].Annotations = annotationsVal1
			} else {
				annotationsVal1 := &AnnotationFilter{}
				_foundServersAnnotations := false
				if _vReadOnlyHint, _ok := _eServers.Get("readOnlyHint"); _ok && _vReadOnlyHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vReadOnlyHint.Leaf); _xok {
						annotationsVal1.ReadOnlyHint = &_x
						_vReadOnlyHint.MarkConsumed()
					}
				}
				if _vDestructiveHint, _ok := _eServers.Get("destructiveHint"); _ok && _vDestructiveHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vDestructiveHint.Leaf); _xok {
						annotationsVal1.DestructiveHint = &_x
						_vDestructiveHint.MarkConsumed()
					}
				}
				if _vIdempotentHint, _ok := _eServers.Get("idempotentHint"); _ok && _vIdempotentHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vIdempotentHint.Leaf); _xok {
						annotationsVal1.IdempotentHint = &_x
						_vIdempotentHint.MarkConsumed()
					}
				}
				if _vOpenWorldHint, _ok := _eServers.Get("openWorldHint"); _ok && _vOpenWorldHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vOpenWorldHint.Leaf); _xok {
						annotationsVal1.OpenWorldHint = &_x
						_vOpenWorldHint.MarkConsumed()
					}
				}
				if _foundServersAnnotations {
					d.data.Servers[i].Annotations = annotationsVal1
				}
			}
			if _vServersPaginate, _ok := _eServers.Get("paginate"); _ok && _vServersPaginate.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersPaginate.Leaf); _xok {
					d.data.Servers[i].Paginate = _x
					_vServersPaginate.MarkConsumed()
				}
			}
			if _vServersGenerateResourceTools, _ok := _eServers.Get("generate-resource-tools"); _ok && _vServersGenerateResourceTools.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersGenerateResourceTools.Leaf); _xok {
					d.data.Servers[i].GenerateResourceTools = &_x
					_vServersGenerateResourceTools.MarkConsumed()
				}
			}
			if _vServersEphemeral, _ok := _eServers.Get("ephemeral"); _ok && _vServersEphemeral.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersEphemeral.Leaf); _xok {
					d.data.Servers[i].Ephemeral = &_x
					_vServersEphemeral.MarkConsumed()
				}
			}
			if _vServersProgressiveDisclosure, _ok := _eServers.Get("progressive-disclosure"); _ok && _vServersProgressiveDisclosure.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersProgressiveDisclosure.Leaf); _xok {
					d.data.Servers[i].ProgressiveDisclosure = &_x
					_vServersProgressiveDisclosure.MarkConsumed()
				}
			}
			if _vServersNixDevshell, _ok := _eServers.Get("nix-devshell"); _ok && _vServersNixDevshell.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersNixDevshell.Leaf); _xok {
					d.data.Servers[i].NixDevshell = &_x
					_vServersNixDevshell.MarkConsumed()
				}
			}
		}
	}
	if _eaServers, _eaok := model.Get("servers"); _eaok && _eaServers.IsEmptyArray() {
		_eaServers.MarkConsumed()
		d.data.Servers = []ServerConfig{}
	}
	return d, nil
}

func (d *ConfigDocument) Data() *Config {
	return &d.data
}

func (d *ConfigDocument) Encode() ([]byte, error) {
	if d.data.Ephemeral != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "ephemeral", *d.data.Ephemeral); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ProgressiveDisclosure != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "progressive-disclosure", *d.data.ProgressiveDisclosure); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.BuiltinNative != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "builtin-native", *d.data.BuiltinNative); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.DisableMoxins) > 0 || cst.HasValue(d.cstDoc.Root(), "disable-moxins") {
			if err := cst.SetAny(d.cstDoc.Root(), "disable-moxins", d.data.DisableMoxins); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(d.data.DisableServers) > 0 || cst.HasValue(d.cstDoc.Root(), "disable-servers") {
			if err := cst.SetAny(d.cstDoc.Root(), "disable-servers", d.data.DisableServers); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Credentials != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "credentials")
		if err := credentials.EncodeCommandConfigFrom(d.data.Credentials, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("credentials: %w", err)
		}
	}
	{
		for i := range d.data.Servers {
			var container *cst.Node
			if i < len(d.servers) {
				container = d.servers[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "servers")
			}
			if d.data.Servers[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.Servers[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				v, err := d.data.Servers[i].Command.MarshalTOML()
				if err != nil {
					return nil, fmt.Errorf("command: %w", err)
				}
				if err := cst.SetAny(container, "command", v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].URL != "" || cst.HasValue(container, "url") {
				if err := cst.SetAny(container, "url", d.data.Servers[i].URL); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].Headers != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "headers")
				cst.DeleteAllValues(tableNode)
				for k, v := range d.data.Servers[i].Headers {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].HeadersHelper != nil {
				if err := cst.SetAny(container, "headers-helper", *d.data.Servers[i].HeadersHelper); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].OAuth != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "oauth")
				if d.data.Servers[i].OAuth.ClientID != "" || cst.HasValue(tableNode, "client-id") {
					if err := cst.SetAny(tableNode, "client-id", d.data.Servers[i].OAuth.ClientID); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].OAuth.CallbackPort != 0 || cst.HasValue(tableNode, "callback-port") {
					if err := cst.SetAny(tableNode, "callback-port", d.data.Servers[i].OAuth.CallbackPort); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].Annotations != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "annotations")
				if d.data.Servers[i].Annotations.ReadOnlyHint != nil {
					if err := cst.SetAny(tableNode, "readOnlyHint", *d.data.Servers[i].Annotations.ReadOnlyHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.DestructiveHint != nil {
					if err := cst.SetAny(tableNode, "destructiveHint", *d.data.Servers[i].Annotations.DestructiveHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.IdempotentHint != nil {
					if err := cst.SetAny(tableNode, "idempotentHint", *d.data.Servers[i].Annotations.IdempotentHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.OpenWorldHint != nil {
					if err := cst.SetAny(tableNode, "openWorldHint", *d.data.Servers[i].Annotations.OpenWorldHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].Paginate != false || cst.HasValue(container, "paginate") {
				if err := cst.SetAny(container, "paginate", d.data.Servers[i].Paginate); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].GenerateResourceTools != nil {
				if err := cst.SetAny(container, "generate-resource-tools", *d.data.Servers[i].GenerateResourceTools); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].Ephemeral != nil {
				if err := cst.SetAny(container, "ephemeral", *d.data.Servers[i].Ephemeral); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].ProgressiveDisclosure != nil {
				if err := cst.SetAny(container, "progressive-disclosure", *d.data.Servers[i].ProgressiveDisclosure); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].NixDevshell != nil {
				if err := cst.SetAny(container, "nix-devshell", *d.data.Servers[i].NixDevshell); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigInto(data *Config, sub *cst.Value) error {
	if _vEphemeral, _ok := sub.Get("ephemeral"); _ok && _vEphemeral.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vEphemeral.Leaf); _xok {
			data.Ephemeral = &_x
			_vEphemeral.MarkConsumed()
		}
	}
	if _vProgressiveDisclosure, _ok := sub.Get("progressive-disclosure"); _ok && _vProgressiveDisclosure.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vProgressiveDisclosure.Leaf); _xok {
			data.ProgressiveDisclosure = &_x
			_vProgressiveDisclosure.MarkConsumed()
		}
	}
	if _vBuiltinNative, _ok := sub.Get("builtin-native"); _ok && _vBuiltinNative.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vBuiltinNative.Leaf); _xok {
			data.BuiltinNative = &_x
			_vBuiltinNative.MarkConsumed()
		}
	}
	if _vDisableMoxins, _ok := sub.Get("disable-moxins"); _ok && _vDisableMoxins.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vDisableMoxins.Leaf); _xok {
			data.DisableMoxins = _x
			if data.DisableMoxins == nil {
				data.DisableMoxins = []string{}
			}
			_vDisableMoxins.MarkConsumed()
		}
	}
	if _vDisableServers, _ok := sub.Get("disable-servers"); _ok && _vDisableServers.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vDisableServers.Leaf); _xok {
			data.DisableServers = _x
			if data.DisableServers == nil {
				data.DisableServers = []string{}
			}
			_vDisableServers.MarkConsumed()
		}
	}
	if _vCredentials, _ok := sub.Get("credentials"); _ok && _vCredentials.Kind == cst.VTable {
		_vCredentials.MarkSeen()
		commandConfigVal := &credentials.CommandConfig{}
		if err := credentials.DecodeCommandConfigInto(commandConfigVal, _vCredentials); err != nil {
			return fmt.Errorf("credentials: %w", err)
		}
		data.Credentials = commandConfigVal
	}
	if _vServers, _ok := sub.Get("servers"); _ok && _vServers.Kind == cst.VArray {
		_vServers.MarkSeen()
		data.Servers = make([]ServerConfig, len(_vServers.Items))
		for i := range _vServers.Items {
			_eServers := &_vServers.Items[i]
			_eServers.MarkSeen()
			if _vServersName, _ok := _eServers.Get("name"); _ok && _vServersName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersName.Leaf); _xok {
					data.Servers[i].Name = _x
					_vServersName.MarkConsumed()
				}
			}
			if _vServersCommand, _ok := _eServers.Get("command"); _ok && _vServersCommand.Kind == cst.VLeaf {
				if _raw, _xok := cst.ExtractRaw(_vServersCommand.Leaf); _xok {
					if err := data.Servers[i].Command.UnmarshalTOML(_raw); err != nil {
						return fmt.Errorf("command: %w", err)
					}
					_vServersCommand.MarkConsumed()
				}
			}
			if _vServersUrl, _ok := _eServers.Get("url"); _ok && _vServersUrl.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersUrl.Leaf); _xok {
					data.Servers[i].URL = _x
					_vServersUrl.MarkConsumed()
				}
			}
			if _vServersHeaders, _ok := _eServers.Get("headers"); _ok && _vServersHeaders.Kind == cst.VTable {
				_vServersHeaders.MarkSeen()
				data.Servers[i].Headers = make(map[string]string)
				for _iServersHeaders := range _vServersHeaders.Fields {
					_fServersHeaders := &_vServersHeaders.Fields[_iServersHeaders]
					if _fServersHeaders.Val.Kind == cst.VLeaf {
						if _s, _sok := cst.ExtractString(_fServersHeaders.Val.Leaf); _sok {
							data.Servers[i].Headers[_fServersHeaders.Key] = _s
							_fServersHeaders.Val.MarkConsumed()
						}
					}
				}
			}
			if _vServersHeadersHelper, _ok := _eServers.Get("headers-helper"); _ok && _vServersHeadersHelper.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersHeadersHelper.Leaf); _xok {
					data.Servers[i].HeadersHelper = &_x
					_vServersHeadersHelper.MarkConsumed()
				}
			}
			if _vServersOauth, _ok := _eServers.Get("oauth"); _ok && _vServersOauth.Kind == cst.VTable {
				_vServersOauth.MarkSeen()
				oAuthVal0 := &OAuthConfig{}
				if _vServersOauthClientId, _ok := _vServersOauth.Get("client-id"); _ok && _vServersOauthClientId.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vServersOauthClientId.Leaf); _xok {
						oAuthVal0.ClientID = _x
						_vServersOauthClientId.MarkConsumed()
					}
				}
				if _vServersOauthCallbackPort, _ok := _vServersOauth.Get("callback-port"); _ok && _vServersOauthCallbackPort.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vServersOauthCallbackPort.Leaf); _xok {
						oAuthVal0.CallbackPort = _x
						_vServersOauthCallbackPort.MarkConsumed()
					}
				}
				data.Servers[i].OAuth = oAuthVal0
			} else {
				oAuthVal0 := &OAuthConfig{}
				_foundServersOauth := false
				if _vClientId, _ok := _eServers.Get("client-id"); _ok && _vClientId.Kind == cst.VLeaf {
					_foundServersOauth = true
					if _x, _xok := cst.ExtractString(_vClientId.Leaf); _xok {
						oAuthVal0.ClientID = _x
						_vClientId.MarkConsumed()
					}
				}
				if _vCallbackPort, _ok := _eServers.Get("callback-port"); _ok && _vCallbackPort.Kind == cst.VLeaf {
					_foundServersOauth = true
					if _x, _xok := cst.ExtractInt(_vCallbackPort.Leaf); _xok {
						oAuthVal0.CallbackPort = _x
						_vCallbackPort.MarkConsumed()
					}
				}
				if _foundServersOauth {
					data.Servers[i].OAuth = oAuthVal0
				}
			}
			if _vServersAnnotations, _ok := _eServers.Get("annotations"); _ok && _vServersAnnotations.Kind == cst.VTable {
				_vServersAnnotations.MarkSeen()
				annotationsVal1 := &AnnotationFilter{}
				if _vServersAnnotationsReadOnlyHint, _ok := _vServersAnnotations.Get("readOnlyHint"); _ok && _vServersAnnotationsReadOnlyHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsReadOnlyHint.Leaf); _xok {
						annotationsVal1.ReadOnlyHint = &_x
						_vServersAnnotationsReadOnlyHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsDestructiveHint, _ok := _vServersAnnotations.Get("destructiveHint"); _ok && _vServersAnnotationsDestructiveHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsDestructiveHint.Leaf); _xok {
						annotationsVal1.DestructiveHint = &_x
						_vServersAnnotationsDestructiveHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsIdempotentHint, _ok := _vServersAnnotations.Get("idempotentHint"); _ok && _vServersAnnotationsIdempotentHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsIdempotentHint.Leaf); _xok {
						annotationsVal1.IdempotentHint = &_x
						_vServersAnnotationsIdempotentHint.MarkConsumed()
					}
				}
				if _vServersAnnotationsOpenWorldHint, _ok := _vServersAnnotations.Get("openWorldHint"); _ok && _vServersAnnotationsOpenWorldHint.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vServersAnnotationsOpenWorldHint.Leaf); _xok {
						annotationsVal1.OpenWorldHint = &_x
						_vServersAnnotationsOpenWorldHint.MarkConsumed()
					}
				}
				data.Servers[i].Annotations = annotationsVal1
			} else {
				annotationsVal1 := &AnnotationFilter{}
				_foundServersAnnotations := false
				if _vReadOnlyHint, _ok := _eServers.Get("readOnlyHint"); _ok && _vReadOnlyHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vReadOnlyHint.Leaf); _xok {
						annotationsVal1.ReadOnlyHint = &_x
						_vReadOnlyHint.MarkConsumed()
					}
				}
				if _vDestructiveHint, _ok := _eServers.Get("destructiveHint"); _ok && _vDestructiveHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vDestructiveHint.Leaf); _xok {
						annotationsVal1.DestructiveHint = &_x
						_vDestructiveHint.MarkConsumed()
					}
				}
				if _vIdempotentHint, _ok := _eServers.Get("idempotentHint"); _ok && _vIdempotentHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vIdempotentHint.Leaf); _xok {
						annotationsVal1.IdempotentHint = &_x
						_vIdempotentHint.MarkConsumed()
					}
				}
				if _vOpenWorldHint, _ok := _eServers.Get("openWorldHint"); _ok && _vOpenWorldHint.Kind == cst.VLeaf {
					_foundServersAnnotations = true
					if _x, _xok := cst.ExtractBool(_vOpenWorldHint.Leaf); _xok {
						annotationsVal1.OpenWorldHint = &_x
						_vOpenWorldHint.MarkConsumed()
					}
				}
				if _foundServersAnnotations {
					data.Servers[i].Annotations = annotationsVal1
				}
			}
			if _vServersPaginate, _ok := _eServers.Get("paginate"); _ok && _vServersPaginate.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersPaginate.Leaf); _xok {
					data.Servers[i].Paginate = _x
					_vServersPaginate.MarkConsumed()
				}
			}
			if _vServersGenerateResourceTools, _ok := _eServers.Get("generate-resource-tools"); _ok && _vServersGenerateResourceTools.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersGenerateResourceTools.Leaf); _xok {
					data.Servers[i].GenerateResourceTools = &_x
					_vServersGenerateResourceTools.MarkConsumed()
				}
			}
			if _vServersEphemeral, _ok := _eServers.Get("ephemeral"); _ok && _vServersEphemeral.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersEphemeral.Leaf); _xok {
					data.Servers[i].Ephemeral = &_x
					_vServersEphemeral.MarkConsumed()
				}
			}
			if _vServersProgressiveDisclosure, _ok := _eServers.Get("progressive-disclosure"); _ok && _vServersProgressiveDisclosure.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractBool(_vServersProgressiveDisclosure.Leaf); _xok {
					data.Servers[i].ProgressiveDisclosure = &_x
					_vServersProgressiveDisclosure.MarkConsumed()
				}
			}
			if _vServersNixDevshell, _ok := _eServers.Get("nix-devshell"); _ok && _vServersNixDevshell.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vServersNixDevshell.Leaf); _xok {
					data.Servers[i].NixDevshell = &_x
					_vServersNixDevshell.MarkConsumed()
				}
			}
		}
	}
	if _eaServers, _eaok := sub.Get("servers"); _eaok && _eaServers.IsEmptyArray() {
		_eaServers.MarkConsumed()
		data.Servers = []ServerConfig{}
	}
	return nil
}

func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	if data.Ephemeral != nil {
		if err := cst.SetAny(container, "ephemeral", *data.Ephemeral); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ProgressiveDisclosure != nil {
		if err := cst.SetAny(container, "progressive-disclosure", *data.ProgressiveDisclosure); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.BuiltinNative != nil {
		if err := cst.SetAny(container, "builtin-native", *data.BuiltinNative); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.DisableMoxins) > 0 || cst.HasValue(container, "disable-moxins") {
			if err := cst.SetAny(container, "disable-moxins", data.DisableMoxins); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(data.DisableServers) > 0 || cst.HasValue(container, "disable-servers") {
			if err := cst.SetAny(container, "disable-servers", data.DisableServers); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Credentials != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "credentials")
		if err := credentials.EncodeCommandConfigFrom(data.Credentials, doc, tableNode); err != nil {
			return fmt.Errorf("credentials: %w", err)
		}
	}
	{
		_apServers := container
		_existServers := cst.FindChildArrayTableNodes(doc.Root(), _apServers, "servers")
		for i := range data.Servers {
			var container *cst.Node
			if i < len(_existServers) {
				container = _existServers[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apServers, "servers")
			}
			if data.Servers[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.Servers[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				v, err := data.Servers[i].Command.MarshalTOML()
				if err != nil {
					return fmt.Errorf("command: %w", err)
				}
				if err := cst.SetAny(container, "command", v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].URL != "" || cst.HasValue(container, "url") {
				if err := cst.SetAny(container, "url", data.Servers[i].URL); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].Headers != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "headers")
				cst.DeleteAllValues(tableNode)
				for k, v := range data.Servers[i].Headers {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].HeadersHelper != nil {
				if err := cst.SetAny(container, "headers-helper", *data.Servers[i].HeadersHelper); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].OAuth != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "oauth")
				if data.Servers[i].OAuth.ClientID != "" || cst.HasValue(tableNode, "client-id") {
					if err := cst.SetAny(tableNode, "client-id", data.Servers[i].OAuth.ClientID); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].OAuth.CallbackPort != 0 || cst.HasValue(tableNode, "callback-port") {
					if err := cst.SetAny(tableNode, "callback-port", data.Servers[i].OAuth.CallbackPort); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].Annotations != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "annotations")
				if data.Servers[i].Annotations.ReadOnlyHint != nil {
					if err := cst.SetAny(tableNode, "readOnlyHint", *data.Servers[i].Annotations.ReadOnlyHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.DestructiveHint != nil {
					if err := cst.SetAny(tableNode, "destructiveHint", *data.Servers[i].Annotations.DestructiveHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.IdempotentHint != nil {
					if err := cst.SetAny(tableNode, "idempotentHint", *data.Servers[i].Annotations.IdempotentHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.OpenWorldHint != nil {
					if err := cst.SetAny(tableNode, "openWorldHint", *data.Servers[i].Annotations.OpenWorldHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].Paginate != false || cst.HasValue(container, "paginate") {
				if err := cst.SetAny(container, "paginate", data.Servers[i].Paginate); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].GenerateResourceTools != nil {
				if err := cst.SetAny(container, "generate-resource-tools", *data.Servers[i].GenerateResourceTools); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].Ephemeral != nil {
				if err := cst.SetAny(container, "ephemeral", *data.Servers[i].Ephemeral); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].ProgressiveDisclosure != nil {
				if err := cst.SetAny(container, "progressive-disclosure", *data.Servers[i].ProgressiveDisclosure); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].NixDevshell != nil {
				if err := cst.SetAny(container, "nix-devshell", *data.Servers[i].NixDevshell); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	return nil
}
