# treefmt-nix configuration. Run via `nix fmt` / `just codemod-fmt-treefmt`
# (write mode); `just lint-fmt` builds the read-only check derivation. The
# `tommy` TOML formatter binary is injected from the flake's tommy input via
# `_module.args.tommy` (see flake.nix's treefmtEval).
{ lib, tommy, ... }:
{
  projectRootFile = "flake.nix";

  # Go: goimports (import grouping) runs first, then gofumpt re-canonicalizes
  # the result. Lower priority runs earlier.
  programs.goimports.enable = true;
  settings.formatter.goimports.priority = 1;
  programs.gofumpt.enable = true;
  settings.formatter.gofumpt.priority = 2;

  programs.nixfmt.enable = true;

  # Shell + bats: 2-space indent, simplify, and case-indent (case branches
  # indented one level past `case`). Covers the zz-tests_bats suite and the
  # moxin/bin shell scripts.
  programs.shfmt.enable = true;
  settings.formatter.shfmt.includes = [
    "*.sh"
    "*.bash"
    "*.bats"
  ];
  settings.formatter.shfmt.options = lib.mkForce [
    "-i"
    "2"
    "-s"
    "-ci"
  ];

  # TypeScript / ESM scripts (bun moxins + zx bin scripts). Scoped to script
  # extensions so prettier does not reformat JSON / YAML / markdown.
  programs.prettier.enable = true;
  settings.formatter.prettier.includes = lib.mkForce [
    "*.ts"
    "*.mjs"
    "*.cjs"
  ];

  # TOML (moxin configs, moxyfile, .moxy/servers/*) via tommy's CST-preserving
  # formatter.
  settings.formatter.tommy = {
    command = "${tommy}/bin/tommy";
    options = [ "fmt" ];
    includes = [ "*.toml" ];
  };

  settings.global.excludes = [
    # Lockfiles / generated manifests — owned by their generators.
    "flake.lock"
    "go.sum"
    "gomod2nix.toml"
    "bun.lock"
    "bun.nix"
    # Generated by `tommy generate`; let go:generate own its formatting.
    "internal/config/config_tommy.go"
    # Test fixtures are loaded/compared verbatim by bats tests.
    "zz-tests_bats/test-fixtures/**"
    # Misc non-source.
    "version.env"
    "sweatfile"
    "LICENSE"
    "*.md"
    "result"
    "result-*"
    ".tmp/**"
    ".direnv/**"
  ];
}
