# treefmt-nix configuration. Run via `nix fmt` / `just codemod-fmt-treefmt`
# (write mode); `just lint-fmt` builds the read-only check derivation. The
# `tommy` TOML formatter binary is injected from the flake's tommy input via
# `_module.args.tommy` (see flake.nix's treefmtEval).
{ lib, tommy, ... }:
{
  projectRootFile = "flake.nix";

  # Go: goimports (import grouping) runs first, then gofumpt re-canonicalizes
  # the result. Lower priority runs earlier.
  programs.goimports.enable = true;
  settings.formatter.goimports.priority = 1;
  programs.gofumpt.enable = true;
  settings.formatter.gofumpt.priority = 2;

  programs.nixfmt.enable = true;

  # Shell + bats: 2-space indent, simplify, and case-indent (case branches
  # indented one level past `case`). Covers the zz-tests_bats suite and the
  # moxin/bin shell scripts.
  programs.shfmt.enable = true;
  settings.formatter.shfmt.includes = [
    "*.sh"
    "*.bash"
    "*.bats"
  ];
  settings.formatter.shfmt.options = lib.mkForce [
    "-i"
    "2"
    "-s"
    "-ci"
  ];

  # TypeScript / ESM scripts (bun moxins + zx bin scripts). Scoped to script
  # extensions so prettier does not reformat JSON / YAML / markdown.
  programs.prettier.enable = true;
  settings.formatter.prettier.includes = lib.mkForce [
    "*.ts"
    "*.mjs"
    "*.cjs"
  ];

  # Python (moxin tool scripts) via ruff: format + lint. Scoped to the
  # first-party moxin Python — the sisyphus lib/ helpers and the
  # sisyphus/freud bin/ tool scripts (almost all pure Python). The
  # extensionless bin scripts are picked up via ruff.toml's extend-include;
  # E402 (import-after-sys.path.insert) is silenced there per-file. Vendored
  # marklas is excluded globally below. api-perms is the one bash script under
  # sisyphus/bin/* — excluded here so treefmt never hands it to ruff (ruff's
  # own extend-exclude loses to extend-include for explicitly-passed paths).
  # See #353 and ./ruff.toml.
  programs.ruff-format.enable = true;
  programs.ruff-check.enable = true;
  settings.formatter.ruff-format.includes = lib.mkForce [
    "moxins/sisyphus/lib/*.py"
    "moxins/sisyphus/bin/*"
    "moxins/freud/bin/*"
  ];
  settings.formatter.ruff-format.excludes = [ "moxins/sisyphus/bin/api-perms" ];
  settings.formatter.ruff-check.includes = lib.mkForce [
    "moxins/sisyphus/lib/*.py"
    "moxins/sisyphus/bin/*"
    "moxins/freud/bin/*"
  ];
  settings.formatter.ruff-check.excludes = [ "moxins/sisyphus/bin/api-perms" ];

  # TOML (moxin configs, moxyfile, .moxy/servers/*) via tommy's CST-preserving
  # formatter.
  settings.formatter.tommy = {
    command = "${tommy}/bin/tommy";
    options = [ "fmt" ];
    includes = [ "*.toml" ];
  };

  settings.global.excludes = [
    # Lockfiles / generated manifests — owned by their generators.
    "flake.lock"
    "go.sum"
    "gomod2nix.toml"
    "bun.lock"
    "bun.nix"
    # Generated by `tommy generate`; let go:generate own its formatting.
    "internal/config/config_tommy.go"
    # Test fixtures are loaded/compared verbatim by bats tests.
    "zz-tests_bats/test-fixtures/**"
    # Vendored marklas (sisyphus) — owned upstream, must not be reformatted.
    "moxins/sisyphus/lib/_vendor/**"
    # Misc non-source.
    "version.env"
    "sweatfile"
    "LICENSE"
    "*.md"
    "result"
    "result-*"
    ".tmp/**"
    ".direnv/**"
  ];
}
