schema = 1
perms-request = "always-allow"
description = "Output the entire justfile contents."
command = "just"
args = ["--dump"]

[input]
type = "object"

[annotations]
read-only-hint = true
idempotent-hint = true
