schema = 1
perms-request = "always-allow"
description = "Run a flake app."
command = "@BIN@/run"
arg_order = ["installable", "args", "flake_dir"]

[input.properties.installable]
type = "string"
description = "Flake installable to run. Defaults to '.#default'."

[input.properties.args]
type = "array"
description = "Arguments to pass to the app."

[input.properties.flake_dir]
type = "string"
description = "Directory containing the flake. Defaults to current directory."

[annotations]
open-world-hint = true
