// Code generated by tommy; DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type FolioConfigDocument struct {
	data     FolioConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeFolioConfig(input []byte) (*FolioConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &FolioConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "permissions"); tableNode != nil {
		d.consumed["permissions"] = true
		permissionsVal := &PermissionConfig{}
		allowNodes := d.cstDoc.FindArrayTableNodes("permissions.allow")
		permissionsVal.Allow = make([]PathRule, len(allowNodes))
		d.consumed["permissions.allow"] = true
		for i, node := range allowNodes {
			if v, err := document.GetFromContainer[[]string](d.cstDoc, node, "path"); err == nil {
				permissionsVal.Allow[i].Path = v
				d.consumed["permissions.allow.path"] = true
			}
		}
		denyNodes := d.cstDoc.FindArrayTableNodes("permissions.deny")
		permissionsVal.Deny = make([]PathRule, len(denyNodes))
		d.consumed["permissions.deny"] = true
		for i, node := range denyNodes {
			if v, err := document.GetFromContainer[[]string](d.cstDoc, node, "path"); err == nil {
				permissionsVal.Deny[i].Path = v
				d.consumed["permissions.deny.path"] = true
			}
		}
		d.data.Permissions = permissionsVal
	} else {
		permissionsVal := &PermissionConfig{}
		found := false
		allowNodes := d.cstDoc.FindArrayTableNodes("permissions.allow")
		if len(allowNodes) > 0 {
			found = true
		}
		permissionsVal.Allow = make([]PathRule, len(allowNodes))
		d.consumed["permissions.allow"] = true
		for i, node := range allowNodes {
			if v, err := document.GetFromContainer[[]string](d.cstDoc, node, "path"); err == nil {
				permissionsVal.Allow[i].Path = v
				d.consumed["permissions.allow.path"] = true
			}
		}
		denyNodes := d.cstDoc.FindArrayTableNodes("permissions.deny")
		if len(denyNodes) > 0 {
			found = true
		}
		permissionsVal.Deny = make([]PathRule, len(denyNodes))
		d.consumed["permissions.deny"] = true
		for i, node := range denyNodes {
			if v, err := document.GetFromContainer[[]string](d.cstDoc, node, "path"); err == nil {
				permissionsVal.Deny[i].Path = v
				d.consumed["permissions.deny.path"] = true
			}
		}
		if found {
			d.data.Permissions = permissionsVal
		}
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "read"); tableNode != nil {
		d.consumed["read"] = true
		readVal := &ReadConfig{}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "max-lines"); err == nil {
			readVal.MaxLines = v
			d.consumed["read.max-lines"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "head-lines"); err == nil {
			readVal.HeadLines = v
			d.consumed["read.head-lines"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "tail-lines"); err == nil {
			readVal.TailLines = v
			d.consumed["read.tail-lines"] = true
		}
		d.data.Read = readVal
	} else {
		readVal := &ReadConfig{}
		found := false
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "max-lines"); err == nil {
			readVal.MaxLines = v
			found = true
			d.consumed["max-lines"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "head-lines"); err == nil {
			readVal.HeadLines = v
			found = true
			d.consumed["head-lines"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "tail-lines"); err == nil {
			readVal.TailLines = v
			found = true
			d.consumed["tail-lines"] = true
		}
		if found {
			d.data.Read = readVal
		}
	}

	return d, nil
}

func (d *FolioConfigDocument) Data() *FolioConfig { return &d.data }

func (d *FolioConfigDocument) Encode() ([]byte, error) {
	if d.data.Permissions != nil {
		_ = d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "permissions")
		{
			allowExisting := d.cstDoc.FindArrayTableNodes("permissions.allow")
			for i := range d.data.Permissions.Allow {
				var container *cst.Node
				if i < len(allowExisting) {
					container = allowExisting[i]
				} else {
					container = d.cstDoc.AppendArrayTableEntry("permissions.allow")
				}
				if err := d.cstDoc.SetInContainer(container, "path", d.data.Permissions.Allow[i].Path); err != nil {
					return nil, err
				}
			}
		}
		{
			denyExisting := d.cstDoc.FindArrayTableNodes("permissions.deny")
			for i := range d.data.Permissions.Deny {
				var container *cst.Node
				if i < len(denyExisting) {
					container = denyExisting[i]
				} else {
					container = d.cstDoc.AppendArrayTableEntry("permissions.deny")
				}
				if err := d.cstDoc.SetInContainer(container, "path", d.data.Permissions.Deny[i].Path); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.Read != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "read")
		if d.data.Read.MaxLines != 0 || d.cstDoc.HasInContainer(tableNode, "max-lines") {
			if err := d.cstDoc.SetInContainer(tableNode, "max-lines", d.data.Read.MaxLines); err != nil {
				return nil, err
			}
		}
		if d.data.Read.HeadLines != 0 || d.cstDoc.HasInContainer(tableNode, "head-lines") {
			if err := d.cstDoc.SetInContainer(tableNode, "head-lines", d.data.Read.HeadLines); err != nil {
				return nil, err
			}
		}
		if d.data.Read.TailLines != 0 || d.cstDoc.HasInContainer(tableNode, "tail-lines") {
			if err := d.cstDoc.SetInContainer(tableNode, "tail-lines", d.data.Read.TailLines); err != nil {
				return nil, err
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *FolioConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *FolioConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *FolioConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *FolioConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *FolioConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeFolioConfigInto(data *FolioConfig, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if tableNode := doc.FindTableInContainer(container, "permissions"); tableNode != nil {
		consumed[keyPrefix+"permissions"] = true
		permissionsVal := &PermissionConfig{}
		allowNodes := doc.FindArrayTableNodes(keyPrefix + "permissions.allow")
		permissionsVal.Allow = make([]PathRule, len(allowNodes))
		consumed[keyPrefix+"permissions.allow"] = true
		for i, node := range allowNodes {
			if v, err := document.GetFromContainer[[]string](doc, node, "path"); err == nil {
				permissionsVal.Allow[i].Path = v
				consumed[keyPrefix+"permissions.allow.path"] = true
			}
		}
		denyNodes := doc.FindArrayTableNodes(keyPrefix + "permissions.deny")
		permissionsVal.Deny = make([]PathRule, len(denyNodes))
		consumed[keyPrefix+"permissions.deny"] = true
		for i, node := range denyNodes {
			if v, err := document.GetFromContainer[[]string](doc, node, "path"); err == nil {
				permissionsVal.Deny[i].Path = v
				consumed[keyPrefix+"permissions.deny.path"] = true
			}
		}
		data.Permissions = permissionsVal
	} else {
		permissionsVal := &PermissionConfig{}
		found := false
		allowNodes := doc.FindArrayTableNodes(keyPrefix + "permissions.allow")
		if len(allowNodes) > 0 {
			found = true
		}
		permissionsVal.Allow = make([]PathRule, len(allowNodes))
		consumed[keyPrefix+"permissions.allow"] = true
		for i, node := range allowNodes {
			if v, err := document.GetFromContainer[[]string](doc, node, "path"); err == nil {
				permissionsVal.Allow[i].Path = v
				consumed[keyPrefix+"permissions.allow.path"] = true
			}
		}
		denyNodes := doc.FindArrayTableNodes(keyPrefix + "permissions.deny")
		if len(denyNodes) > 0 {
			found = true
		}
		permissionsVal.Deny = make([]PathRule, len(denyNodes))
		consumed[keyPrefix+"permissions.deny"] = true
		for i, node := range denyNodes {
			if v, err := document.GetFromContainer[[]string](doc, node, "path"); err == nil {
				permissionsVal.Deny[i].Path = v
				consumed[keyPrefix+"permissions.deny.path"] = true
			}
		}
		if found {
			data.Permissions = permissionsVal
		}
	}
	if tableNode := doc.FindTableInContainer(container, "read"); tableNode != nil {
		consumed[keyPrefix+"read"] = true
		readVal := &ReadConfig{}
		if v, err := document.GetFromContainer[int](doc, tableNode, "max-lines"); err == nil {
			readVal.MaxLines = v
			consumed[keyPrefix+"read.max-lines"] = true
		}
		if v, err := document.GetFromContainer[int](doc, tableNode, "head-lines"); err == nil {
			readVal.HeadLines = v
			consumed[keyPrefix+"read.head-lines"] = true
		}
		if v, err := document.GetFromContainer[int](doc, tableNode, "tail-lines"); err == nil {
			readVal.TailLines = v
			consumed[keyPrefix+"read.tail-lines"] = true
		}
		data.Read = readVal
	} else {
		readVal := &ReadConfig{}
		found := false
		if v, err := document.GetFromContainer[int](doc, container, "max-lines"); err == nil {
			readVal.MaxLines = v
			found = true
			consumed[keyPrefix+"max-lines"] = true
		}
		if v, err := document.GetFromContainer[int](doc, container, "head-lines"); err == nil {
			readVal.HeadLines = v
			found = true
			consumed[keyPrefix+"head-lines"] = true
		}
		if v, err := document.GetFromContainer[int](doc, container, "tail-lines"); err == nil {
			readVal.TailLines = v
			found = true
			consumed[keyPrefix+"tail-lines"] = true
		}
		if found {
			data.Read = readVal
		}
	}

	return nil
}

func EncodeFolioConfigFrom(data *FolioConfig, doc *document.Document, container *cst.Node) error {
	if data.Permissions != nil {
		_ = doc.EnsureTableInContainer(container, "permissions")
		{
			allowExisting := doc.FindArrayTableNodes("permissions.allow")
			for i := range data.Permissions.Allow {
				var container *cst.Node
				if i < len(allowExisting) {
					container = allowExisting[i]
				} else {
					container = doc.AppendArrayTableEntry("permissions.allow")
				}
				if err := doc.SetInContainer(container, "path", data.Permissions.Allow[i].Path); err != nil {
					return err
				}
			}
		}
		{
			denyExisting := doc.FindArrayTableNodes("permissions.deny")
			for i := range data.Permissions.Deny {
				var container *cst.Node
				if i < len(denyExisting) {
					container = denyExisting[i]
				} else {
					container = doc.AppendArrayTableEntry("permissions.deny")
				}
				if err := doc.SetInContainer(container, "path", data.Permissions.Deny[i].Path); err != nil {
					return err
				}
			}
		}
	}
	if data.Read != nil {
		tableNode := doc.EnsureTableInContainer(container, "read")
		if data.Read.MaxLines != 0 || doc.HasInContainer(tableNode, "max-lines") {
			if err := doc.SetInContainer(tableNode, "max-lines", data.Read.MaxLines); err != nil {
				return err
			}
		}
		if data.Read.HeadLines != 0 || doc.HasInContainer(tableNode, "head-lines") {
			if err := doc.SetInContainer(tableNode, "head-lines", data.Read.HeadLines); err != nil {
				return err
			}
		}
		if data.Read.TailLines != 0 || doc.HasInContainer(tableNode, "tail-lines") {
			if err := doc.SetInContainer(tableNode, "tail-lines", data.Read.TailLines); err != nil {
				return err
			}
		}
	}

	return nil
}
