// Code generated by tommy; DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type ManeaterConfigDocument struct {
	data     ManeaterConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeManeaterConfig(input []byte) (*ManeaterConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ManeaterConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "default"); err == nil {
		d.data.Default = v
		d.consumed["default"] = true
	}
	{
		subTables := d.cstDoc.FindSubTables("models")
		if len(subTables) > 0 {
			d.consumed["models"] = true
			d.data.Models = make(map[string]ModelConfig)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "models")
				d.consumed["models"+"."+mapKey] = true
				var entry ModelConfig
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "path"); err == nil {
					entry.Path = v
					d.consumed["models.\" + mapKey + \".path"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "query-prefix"); err == nil {
					entry.QueryPrefix = v
					d.consumed["models.\" + mapKey + \".query-prefix"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "document-prefix"); err == nil {
					entry.DocumentPrefix = v
					d.consumed["models.\" + mapKey + \".document-prefix"] = true
				}
				d.data.Models[mapKey] = entry
			}
		}
	}

	return d, nil
}

func (d *ManeaterConfigDocument) Data() *ManeaterConfig { return &d.data }

func (d *ManeaterConfigDocument) Encode() ([]byte, error) {
	if d.data.Default != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "default") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "default", d.data.Default); err != nil {
			return nil, err
		}
	}
	if len(d.data.Models) > 0 {
		for mapKey, mapVal := range d.data.Models {
			subTable := d.cstDoc.EnsureSubTable("models", mapKey)
			if mapVal.Path != "" || d.cstDoc.HasInContainer(subTable, "path") {
				if err := d.cstDoc.SetInContainer(subTable, "path", mapVal.Path); err != nil {
					return nil, err
				}
			}
			if mapVal.QueryPrefix != "" || d.cstDoc.HasInContainer(subTable, "query-prefix") {
				if err := d.cstDoc.SetInContainer(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return nil, err
				}
			}
			if mapVal.DocumentPrefix != "" || d.cstDoc.HasInContainer(subTable, "document-prefix") {
				if err := d.cstDoc.SetInContainer(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return nil, err
				}
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *ManeaterConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *ManeaterConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ManeaterConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ManeaterConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ManeaterConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeManeaterConfigInto(data *ManeaterConfig, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[string](doc, container, "default"); err == nil {
		data.Default = v
		consumed[keyPrefix+"default"] = true
	}
	{
		subTables := doc.FindSubTables("models")
		if len(subTables) > 0 {
			consumed[keyPrefix+"models"] = true
			data.Models = make(map[string]ModelConfig)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "models")
				consumed[keyPrefix+"models"+"."+mapKey] = true
				var entry ModelConfig
				if v, err := document.GetFromContainer[string](doc, subTable, "path"); err == nil {
					entry.Path = v
					consumed[keyPrefix+"models.\" + mapKey + \".path"] = true
				}
				if v, err := document.GetFromContainer[string](doc, subTable, "query-prefix"); err == nil {
					entry.QueryPrefix = v
					consumed[keyPrefix+"models.\" + mapKey + \".query-prefix"] = true
				}
				if v, err := document.GetFromContainer[string](doc, subTable, "document-prefix"); err == nil {
					entry.DocumentPrefix = v
					consumed[keyPrefix+"models.\" + mapKey + \".document-prefix"] = true
				}
				data.Models[mapKey] = entry
			}
		}
	}

	return nil
}

func EncodeManeaterConfigFrom(data *ManeaterConfig, doc *document.Document, container *cst.Node) error {
	if data.Default != "" || doc.HasInContainer(container, "default") {
		if err := doc.SetInContainer(container, "default", data.Default); err != nil {
			return err
		}
	}
	if len(data.Models) > 0 {
		for mapKey, mapVal := range data.Models {
			subTable := doc.EnsureSubTable("models", mapKey)
			if mapVal.Path != "" || doc.HasInContainer(subTable, "path") {
				if err := doc.SetInContainer(subTable, "path", mapVal.Path); err != nil {
					return err
				}
			}
			if mapVal.QueryPrefix != "" || doc.HasInContainer(subTable, "query-prefix") {
				if err := doc.SetInContainer(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return err
				}
			}
			if mapVal.DocumentPrefix != "" || doc.HasInContainer(subTable, "document-prefix") {
				if err := doc.SetInContainer(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return err
				}
			}
		}
	}

	return nil
}
