// Code generated by tommy; DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type FreudConfigDocument struct {
	data     FreudConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeFreudConfig(input []byte) (*FreudConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &FreudConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "projects-dir"); err == nil {
		d.data.ProjectsDir = v
		d.consumed["projects-dir"] = true
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "list"); tableNode != nil {
		d.consumed["list"] = true
		listVal := &ListConfig{}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "max-rows"); err == nil {
			listVal.MaxRows = v
			d.consumed["list.max-rows"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "head-rows"); err == nil {
			listVal.HeadRows = v
			d.consumed["list.head-rows"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "tail-rows"); err == nil {
			listVal.TailRows = v
			d.consumed["list.tail-rows"] = true
		}
		d.data.List = listVal
	} else {
		listVal := &ListConfig{}
		found := false
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "max-rows"); err == nil {
			listVal.MaxRows = v
			found = true
			d.consumed["max-rows"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "head-rows"); err == nil {
			listVal.HeadRows = v
			found = true
			d.consumed["head-rows"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "tail-rows"); err == nil {
			listVal.TailRows = v
			found = true
			d.consumed["tail-rows"] = true
		}
		if found {
			d.data.List = listVal
		}
	}

	return d, nil
}

func (d *FreudConfigDocument) Data() *FreudConfig { return &d.data }

func (d *FreudConfigDocument) Encode() ([]byte, error) {
	if d.data.ProjectsDir != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "projects-dir") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "projects-dir", d.data.ProjectsDir); err != nil {
			return nil, err
		}
	}
	if d.data.List != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "list")
		if d.data.List.MaxRows != 0 || d.cstDoc.HasInContainer(tableNode, "max-rows") {
			if err := d.cstDoc.SetInContainer(tableNode, "max-rows", d.data.List.MaxRows); err != nil {
				return nil, err
			}
		}
		if d.data.List.HeadRows != 0 || d.cstDoc.HasInContainer(tableNode, "head-rows") {
			if err := d.cstDoc.SetInContainer(tableNode, "head-rows", d.data.List.HeadRows); err != nil {
				return nil, err
			}
		}
		if d.data.List.TailRows != 0 || d.cstDoc.HasInContainer(tableNode, "tail-rows") {
			if err := d.cstDoc.SetInContainer(tableNode, "tail-rows", d.data.List.TailRows); err != nil {
				return nil, err
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *FreudConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *FreudConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *FreudConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *FreudConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *FreudConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeFreudConfigInto(data *FreudConfig, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[string](doc, container, "projects-dir"); err == nil {
		data.ProjectsDir = v
		consumed[keyPrefix+"projects-dir"] = true
	}
	if tableNode := doc.FindTableInContainer(container, "list"); tableNode != nil {
		consumed[keyPrefix+"list"] = true
		listVal := &ListConfig{}
		if v, err := document.GetFromContainer[int](doc, tableNode, "max-rows"); err == nil {
			listVal.MaxRows = v
			consumed[keyPrefix+"list.max-rows"] = true
		}
		if v, err := document.GetFromContainer[int](doc, tableNode, "head-rows"); err == nil {
			listVal.HeadRows = v
			consumed[keyPrefix+"list.head-rows"] = true
		}
		if v, err := document.GetFromContainer[int](doc, tableNode, "tail-rows"); err == nil {
			listVal.TailRows = v
			consumed[keyPrefix+"list.tail-rows"] = true
		}
		data.List = listVal
	} else {
		listVal := &ListConfig{}
		found := false
		if v, err := document.GetFromContainer[int](doc, container, "max-rows"); err == nil {
			listVal.MaxRows = v
			found = true
			consumed[keyPrefix+"max-rows"] = true
		}
		if v, err := document.GetFromContainer[int](doc, container, "head-rows"); err == nil {
			listVal.HeadRows = v
			found = true
			consumed[keyPrefix+"head-rows"] = true
		}
		if v, err := document.GetFromContainer[int](doc, container, "tail-rows"); err == nil {
			listVal.TailRows = v
			found = true
			consumed[keyPrefix+"tail-rows"] = true
		}
		if found {
			data.List = listVal
		}
	}

	return nil
}

func EncodeFreudConfigFrom(data *FreudConfig, doc *document.Document, container *cst.Node) error {
	if data.ProjectsDir != "" || doc.HasInContainer(container, "projects-dir") {
		if err := doc.SetInContainer(container, "projects-dir", data.ProjectsDir); err != nil {
			return err
		}
	}
	if data.List != nil {
		tableNode := doc.EnsureTableInContainer(container, "list")
		if data.List.MaxRows != 0 || doc.HasInContainer(tableNode, "max-rows") {
			if err := doc.SetInContainer(tableNode, "max-rows", data.List.MaxRows); err != nil {
				return err
			}
		}
		if data.List.HeadRows != 0 || doc.HasInContainer(tableNode, "head-rows") {
			if err := doc.SetInContainer(tableNode, "head-rows", data.List.HeadRows); err != nil {
				return err
			}
		}
		if data.List.TailRows != 0 || doc.HasInContainer(tableNode, "tail-rows") {
			if err := doc.SetInContainer(tableNode, "tail-rows", data.List.TailRows); err != nil {
				return err
			}
		}
	}

	return nil
}
