// Code generated by tommy; DO NOT EDIT.

package config

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type serverConfigHandle struct {
	node *cst.Node
}

type ConfigDocument struct {
	data    Config
	cstDoc  *document.Document
	servers []serverConfigHandle
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{cstDoc: doc}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "ephemeral"); err == nil {
		d.data.Ephemeral = &v
	}
	serversNodes := d.cstDoc.FindArrayTableNodes("servers")
	d.servers = make([]serverConfigHandle, len(serversNodes))
	d.data.Servers = make([]ServerConfig, len(serversNodes))
	for i, node := range serversNodes {
		d.servers[i] = serverConfigHandle{node: node}
		if v, err := document.GetFromContainer[string](d.cstDoc, node, "name"); err == nil {
			d.data.Servers[i].Name = v
		}
		if raw, err := document.GetRawFromContainer(d.cstDoc, node, "command"); err == nil {
			if err := d.data.Servers[i].Command.UnmarshalTOML(raw); err != nil {
				return nil, fmt.Errorf("command: %w", err)
			}
		}
		if tableNode := d.cstDoc.FindTableInContainer(node, "annotations"); tableNode != nil {
			annotationsVal := &AnnotationFilter{}
			if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "readOnlyHint"); err == nil {
				annotationsVal.ReadOnlyHint = &v
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "destructiveHint"); err == nil {
				annotationsVal.DestructiveHint = &v
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "idempotentHint"); err == nil {
				annotationsVal.IdempotentHint = &v
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "openWorldHint"); err == nil {
				annotationsVal.OpenWorldHint = &v
			}
			d.data.Servers[i].Annotations = annotationsVal
		} else {
			annotationsVal := &AnnotationFilter{}
			found := false
			if v, err := document.GetFromContainer[bool](d.cstDoc, node, "readOnlyHint"); err == nil {
				annotationsVal.ReadOnlyHint = &v
				found = true
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, node, "destructiveHint"); err == nil {
				annotationsVal.DestructiveHint = &v
				found = true
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, node, "idempotentHint"); err == nil {
				annotationsVal.IdempotentHint = &v
				found = true
			}
			if v, err := document.GetFromContainer[bool](d.cstDoc, node, "openWorldHint"); err == nil {
				annotationsVal.OpenWorldHint = &v
				found = true
			}
			if found {
				d.data.Servers[i].Annotations = annotationsVal
			}
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, node, "paginate"); err == nil {
			d.data.Servers[i].Paginate = v
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, node, "generate-resource-tools"); err == nil {
			d.data.Servers[i].GenerateResourceTools = &v
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, node, "ephemeral"); err == nil {
			d.data.Servers[i].Ephemeral = &v
		}
	}

	return d, nil
}

func (d *ConfigDocument) Data() *Config { return &d.data }

func (d *ConfigDocument) Encode() ([]byte, error) {
	if d.data.Ephemeral != nil {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "ephemeral", *d.data.Ephemeral); err != nil {
			return nil, err
		}
	}
	for i := range d.data.Servers {
		var container *cst.Node
		if i < len(d.servers) {
			container = d.servers[i].node
		} else {
			container = d.cstDoc.AppendArrayTableEntry("servers")
		}
		if d.data.Servers[i].Name != "" || d.cstDoc.HasInContainer(container, "name") {
			if err := d.cstDoc.SetInContainer(container, "name", d.data.Servers[i].Name); err != nil {
				return nil, err
			}
		}
		{
			v, err := d.data.Servers[i].Command.MarshalTOML()
			if err != nil {
				return nil, fmt.Errorf("command: %w", err)
			}
			if err := d.cstDoc.SetInContainer(container, "command", v); err != nil {
				return nil, err
			}
		}
		if d.data.Servers[i].Paginate != false || d.cstDoc.HasInContainer(container, "paginate") {
			if err := d.cstDoc.SetInContainer(container, "paginate", d.data.Servers[i].Paginate); err != nil {
				return nil, err
			}
		}
		if d.data.Servers[i].GenerateResourceTools != nil {
			if err := d.cstDoc.SetInContainer(container, "generate-resource-tools", *d.data.Servers[i].GenerateResourceTools); err != nil {
				return nil, err
			}
		}
		if d.data.Servers[i].Ephemeral != nil {
			if err := d.cstDoc.SetInContainer(container, "ephemeral", *d.data.Servers[i].Ephemeral); err != nil {
				return nil, err
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}
