// Code generated by tommy; DO NOT EDIT.

package config

import (
	"fmt"
	"github.com/amarbel-llc/moxy/internal/credentials"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type pavedPathConfigHandle struct {
	node *cst.Node
}
type serverConfigHandle struct {
	node *cst.Node
}
type ConfigDocument struct {
	data       Config
	cstDoc     *document.Document
	consumed   map[string]bool
	pavedPaths []pavedPathConfigHandle
	servers    []serverConfigHandle
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "ephemeral":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.Ephemeral = &v
				d.consumed["ephemeral"] = true
			}
		case "progressive-disclosure":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.ProgressiveDisclosure = &v
				d.consumed["progressive-disclosure"] = true
			}
		case "builtin-native":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.BuiltinNative = &v
				d.consumed["builtin-native"] = true
			}
		case "disable-moxins":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.DisableMoxins = v
				d.consumed["disable-moxins"] = true
			}
		}
	}
	var _nodesPavedPaths []*cst.Node
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_ch) == "paved-paths" {
			_nodesPavedPaths = append(_nodesPavedPaths, _ch)
		}
	}
	d.pavedPaths = make([]pavedPathConfigHandle, len(_nodesPavedPaths))
	d.data.PavedPaths = make([]PavedPathConfig, len(_nodesPavedPaths))
	d.consumed["paved-paths"] = true
	for i, _node := range _nodesPavedPaths {
		d.pavedPaths[i] = pavedPathConfigHandle{node: _node}
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.PavedPaths[i].Name = v
					d.consumed["paved-paths.name"] = true
				}
			case "description":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.PavedPaths[i].Description = v
					d.consumed["paved-paths.description"] = true
				}
			}
		}
		{
			var _stagesNodes []*cst.Node
			_pi := 0
			_inScope := false
			for _, _rc := range d.cstDoc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable {
					_hdr := cst.TableHeaderKey(_rc)
					if _hdr == "paved-paths" {
						if _pi == i {
							_inScope = true
						} else if _pi > i {
							break
						}
						_pi++
						continue
					}
					if _inScope && _hdr == "paved-paths.stages" {
						_stagesNodes = append(_stagesNodes, _rc)
					}
				}
			}
			d.data.PavedPaths[i].Stages = make([]PavedPathStage, len(_stagesNodes))
			d.consumed["paved-paths.stages"] = true
			for _ii, _nn := range _stagesNodes {
				for _, _kv := range _nn.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "label":
						if v, ok := cst.ExtractString(_kv); ok {
							d.data.PavedPaths[i].Stages[_ii].Label = v
							d.consumed["paved-paths.stages.label"] = true
						}
					case "tools":
						if v, ok := cst.ExtractStringSlice(_kv); ok {
							d.data.PavedPaths[i].Stages[_ii].Tools = v
							d.consumed["paved-paths.stages.tools"] = true
						}
					}
				}
			}
		}
	}
	{
		var _tblCredentials *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "credentials" {
				_tblCredentials = _ch
				break
			}
		}
		if _tblCredentials != nil {
			d.consumed["credentials"] = true
			commandConfigVal := &credentials.CommandConfig{}
			if err := credentials.DecodeCommandConfigInto(commandConfigVal, d.cstDoc, _tblCredentials, d.consumed, "credentials."); err != nil {
				return nil, fmt.Errorf("credentials: %w", err)
			}
			d.data.Credentials = commandConfigVal
		}
	}
	var _nodesServers []*cst.Node
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_ch) == "servers" {
			_nodesServers = append(_nodesServers, _ch)
		}
	}
	d.servers = make([]serverConfigHandle, len(_nodesServers))
	d.data.Servers = make([]ServerConfig, len(_nodesServers))
	d.consumed["servers"] = true
	for i, _node := range _nodesServers {
		d.servers[i] = serverConfigHandle{node: _node}
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.Servers[i].Name = v
					d.consumed["servers.name"] = true
				}
			case "command":
				if raw, ok := cst.ExtractRaw(_kv); ok {
					if err := d.data.Servers[i].Command.UnmarshalTOML(raw); err != nil {
						return nil, fmt.Errorf("command: %w", err)
					}
					d.consumed["servers.command"] = true
				}
			case "url":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.Servers[i].URL = v
					d.consumed["servers.url"] = true
				}
			case "headers-helper":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.Servers[i].HeadersHelper = &v
					d.consumed["servers.headers-helper"] = true
				}
			case "paginate":
				if v, ok := cst.ExtractBool(_kv); ok {
					d.data.Servers[i].Paginate = v
					d.consumed["servers.paginate"] = true
				}
			case "generate-resource-tools":
				if v, ok := cst.ExtractBool(_kv); ok {
					d.data.Servers[i].GenerateResourceTools = &v
					d.consumed["servers.generate-resource-tools"] = true
				}
			case "ephemeral":
				if v, ok := cst.ExtractBool(_kv); ok {
					d.data.Servers[i].Ephemeral = &v
					d.consumed["servers.ephemeral"] = true
				}
			case "progressive-disclosure":
				if v, ok := cst.ExtractBool(_kv); ok {
					d.data.Servers[i].ProgressiveDisclosure = &v
					d.consumed["servers.progressive-disclosure"] = true
				}
			case "nix-devshell":
				if v, ok := cst.ExtractString(_kv); ok {
					d.data.Servers[i].NixDevshell = &v
					d.consumed["servers.nix-devshell"] = true
				}
			}
		}
		{
			_pi := 0
			for _, _rc := range d.cstDoc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == "servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == "servers.headers" {
					d.data.Servers[i].Headers = cst.ExtractStringMap(_rc)
					d.consumed["servers.headers"] = true
					for _ik := range d.data.Servers[i].Headers {
						d.consumed["servers.headers"+"."+_ik] = true
					}
					break
				}
			}
		}
		{
			var _ftServersOauth *cst.Node
			_pi := 0
			for _, _rc := range d.cstDoc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == "servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == "servers.oauth" {
					_ftServersOauth = _rc
					break
				}
			}
			if _ftServersOauth != nil {
				d.consumed["servers.oauth"] = true
				oAuthVal := &OAuthConfig{}
				for _, _kv := range _ftServersOauth.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "client-id":
						if v, ok := cst.ExtractString(_kv); ok {
							oAuthVal.ClientID = v
							d.consumed["servers.oauth.client-id"] = true
						}
					case "callback-port":
						if v, ok := cst.ExtractInt(_kv); ok {
							oAuthVal.CallbackPort = v
							d.consumed["servers.oauth.callback-port"] = true
						}
					}
				}
				d.data.Servers[i].OAuth = oAuthVal
			} else {
				oAuthVal := &OAuthConfig{}
				_found := false
				for _, _kv := range _node.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "client-id":
						if v, ok := cst.ExtractString(_kv); ok {
							oAuthVal.ClientID = v
							_found = true
							d.consumed["client-id"] = true
						}
					case "callback-port":
						if v, ok := cst.ExtractInt(_kv); ok {
							oAuthVal.CallbackPort = v
							_found = true
							d.consumed["callback-port"] = true
						}
					}
				}
				if _found {
					d.data.Servers[i].OAuth = oAuthVal
				}
			}
		}
		{
			var _ftServersAnnotations *cst.Node
			_pi := 0
			for _, _rc := range d.cstDoc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == "servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == "servers.annotations" {
					_ftServersAnnotations = _rc
					break
				}
			}
			if _ftServersAnnotations != nil {
				d.consumed["servers.annotations"] = true
				annotationsVal := &AnnotationFilter{}
				for _, _kv := range _ftServersAnnotations.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "readOnlyHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.ReadOnlyHint = &v
							d.consumed["servers.annotations.readOnlyHint"] = true
						}
					case "destructiveHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.DestructiveHint = &v
							d.consumed["servers.annotations.destructiveHint"] = true
						}
					case "idempotentHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.IdempotentHint = &v
							d.consumed["servers.annotations.idempotentHint"] = true
						}
					case "openWorldHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.OpenWorldHint = &v
							d.consumed["servers.annotations.openWorldHint"] = true
						}
					}
				}
				d.data.Servers[i].Annotations = annotationsVal
			} else {
				annotationsVal := &AnnotationFilter{}
				_found := false
				for _, _kv := range _node.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "readOnlyHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.ReadOnlyHint = &v
							_found = true
							d.consumed["readOnlyHint"] = true
						}
					case "destructiveHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.DestructiveHint = &v
							_found = true
							d.consumed["destructiveHint"] = true
						}
					case "idempotentHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.IdempotentHint = &v
							_found = true
							d.consumed["idempotentHint"] = true
						}
					case "openWorldHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.OpenWorldHint = &v
							_found = true
							d.consumed["openWorldHint"] = true
						}
					}
				}
				if _found {
					d.data.Servers[i].Annotations = annotationsVal
				}
			}
		}
	}
	return d, nil
}
func (d *ConfigDocument) Data() *Config {
	return &d.data
}
func (d *ConfigDocument) Encode() ([]byte, error) {
	if d.data.Ephemeral != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "ephemeral", *d.data.Ephemeral); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ProgressiveDisclosure != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "progressive-disclosure", *d.data.ProgressiveDisclosure); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.BuiltinNative != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "builtin-native", *d.data.BuiltinNative); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.DisableMoxins) > 0 || cst.HasValue(d.cstDoc.Root(), "disable-moxins") {
			if err := cst.SetAny(d.cstDoc.Root(), "disable-moxins", d.data.DisableMoxins); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		for i := range d.data.PavedPaths {
			var container *cst.Node
			if i < len(d.pavedPaths) {
				container = d.pavedPaths[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "paved-paths")
			}
			if d.data.PavedPaths[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.PavedPaths[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.PavedPaths[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", d.data.PavedPaths[i].Description); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				_existPavedPathsStages := cst.FindArrayTableNodes(d.cstDoc.Root(), "paved-paths.stages")
				for i := range d.data.PavedPaths[i].Stages {
					var container *cst.Node
					if i < len(_existPavedPathsStages) {
						container = _existPavedPathsStages[i]
					} else {
						container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "paved-paths.stages")
					}
					if d.data.PavedPaths[i].Stages[i].Label != "" || cst.HasValue(container, "label") {
						if err := cst.SetAny(container, "label", d.data.PavedPaths[i].Stages[i].Label); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
					{
						if len(d.data.PavedPaths[i].Stages[i].Tools) > 0 || cst.HasValue(container, "tools") {
							if err := cst.SetAny(container, "tools", d.data.PavedPaths[i].Stages[i].Tools); err != nil {
								return nil, fmt.Errorf("%w", err)
							}
						}
					}
				}
			}
		}
	}
	if d.data.Credentials != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "credentials")
		if err := credentials.EncodeCommandConfigFrom(d.data.Credentials, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("credentials: %w", err)
		}
	}
	{
		for i := range d.data.Servers {
			var container *cst.Node
			if i < len(d.servers) {
				container = d.servers[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "servers")
			}
			if d.data.Servers[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.Servers[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				v, err := d.data.Servers[i].Command.MarshalTOML()
				if err != nil {
					return nil, fmt.Errorf("command: %w", err)
				}
				if err := cst.SetAny(container, "command", v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].URL != "" || cst.HasValue(container, "url") {
				if err := cst.SetAny(container, "url", d.data.Servers[i].URL); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if len(d.data.Servers[i].Headers) > 0 {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "headers")
				cst.DeleteAllValues(tableNode)
				for k, v := range d.data.Servers[i].Headers {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].HeadersHelper != nil {
				if err := cst.SetAny(container, "headers-helper", *d.data.Servers[i].HeadersHelper); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].OAuth != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "oauth")
				if d.data.Servers[i].OAuth.ClientID != "" || cst.HasValue(tableNode, "client-id") {
					if err := cst.SetAny(tableNode, "client-id", d.data.Servers[i].OAuth.ClientID); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].OAuth.CallbackPort != 0 || cst.HasValue(tableNode, "callback-port") {
					if err := cst.SetAny(tableNode, "callback-port", d.data.Servers[i].OAuth.CallbackPort); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].Annotations != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), container, "annotations")
				if d.data.Servers[i].Annotations.ReadOnlyHint != nil {
					if err := cst.SetAny(tableNode, "readOnlyHint", *d.data.Servers[i].Annotations.ReadOnlyHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.DestructiveHint != nil {
					if err := cst.SetAny(tableNode, "destructiveHint", *d.data.Servers[i].Annotations.DestructiveHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.IdempotentHint != nil {
					if err := cst.SetAny(tableNode, "idempotentHint", *d.data.Servers[i].Annotations.IdempotentHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Servers[i].Annotations.OpenWorldHint != nil {
					if err := cst.SetAny(tableNode, "openWorldHint", *d.data.Servers[i].Annotations.OpenWorldHint); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Servers[i].Paginate != false || cst.HasValue(container, "paginate") {
				if err := cst.SetAny(container, "paginate", d.data.Servers[i].Paginate); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].GenerateResourceTools != nil {
				if err := cst.SetAny(container, "generate-resource-tools", *d.data.Servers[i].GenerateResourceTools); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].Ephemeral != nil {
				if err := cst.SetAny(container, "ephemeral", *d.data.Servers[i].Ephemeral); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].ProgressiveDisclosure != nil {
				if err := cst.SetAny(container, "progressive-disclosure", *d.data.Servers[i].ProgressiveDisclosure); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Servers[i].NixDevshell != nil {
				if err := cst.SetAny(container, "nix-devshell", *d.data.Servers[i].NixDevshell); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *ConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeConfigInto(data *Config, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "ephemeral":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.Ephemeral = &v
				consumed[keyPrefix+"ephemeral"] = true
			}
		case "progressive-disclosure":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.ProgressiveDisclosure = &v
				consumed[keyPrefix+"progressive-disclosure"] = true
			}
		case "builtin-native":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.BuiltinNative = &v
				consumed[keyPrefix+"builtin-native"] = true
			}
		case "disable-moxins":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.DisableMoxins = v
				consumed[keyPrefix+"disable-moxins"] = true
			}
		}
	}
	var _nodesPavedPaths []*cst.Node
	_nodesPavedPaths = doc.FindArrayTableNodes(keyPrefix + "paved-paths")
	data.PavedPaths = make([]PavedPathConfig, len(_nodesPavedPaths))
	consumed[keyPrefix+"paved-paths"] = true
	for i, _node := range _nodesPavedPaths {
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					data.PavedPaths[i].Name = v
					consumed[keyPrefix+"paved-paths.name"] = true
				}
			case "description":
				if v, ok := cst.ExtractString(_kv); ok {
					data.PavedPaths[i].Description = v
					consumed[keyPrefix+"paved-paths.description"] = true
				}
			}
		}
		{
			var _stagesNodes []*cst.Node
			_pi := 0
			_inScope := false
			for _, _rc := range doc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable {
					_hdr := cst.TableHeaderKey(_rc)
					if _hdr == keyPrefix+"paved-paths" {
						if _pi == i {
							_inScope = true
						} else if _pi > i {
							break
						}
						_pi++
						continue
					}
					if _inScope && _hdr == keyPrefix+"paved-paths.stages" {
						_stagesNodes = append(_stagesNodes, _rc)
					}
				}
			}
			data.PavedPaths[i].Stages = make([]PavedPathStage, len(_stagesNodes))
			consumed[keyPrefix+"paved-paths.stages"] = true
			for _ii, _nn := range _stagesNodes {
				for _, _kv := range _nn.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "label":
						if v, ok := cst.ExtractString(_kv); ok {
							data.PavedPaths[i].Stages[_ii].Label = v
							consumed[keyPrefix+"paved-paths.stages.label"] = true
						}
					case "tools":
						if v, ok := cst.ExtractStringSlice(_kv); ok {
							data.PavedPaths[i].Stages[_ii].Tools = v
							consumed[keyPrefix+"paved-paths.stages.tools"] = true
						}
					}
				}
			}
		}
	}
	{
		var _tblCredentials *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"credentials" {
				_tblCredentials = _ch
				break
			}
		}
		if _tblCredentials != nil {
			consumed[keyPrefix+"credentials"] = true
			commandConfigVal := &credentials.CommandConfig{}
			if err := credentials.DecodeCommandConfigInto(commandConfigVal, doc, _tblCredentials, consumed, keyPrefix+"credentials."); err != nil {
				return fmt.Errorf("credentials: %w", err)
			}
			data.Credentials = commandConfigVal
		}
	}
	var _nodesServers []*cst.Node
	_nodesServers = doc.FindArrayTableNodes(keyPrefix + "servers")
	data.Servers = make([]ServerConfig, len(_nodesServers))
	consumed[keyPrefix+"servers"] = true
	for i, _node := range _nodesServers {
		for _, _kv := range _node.Children {
			if _kv.Kind != cst.NodeKeyValue {
				continue
			}
			switch cst.KeyValueName(_kv) {
			case "name":
				if v, ok := cst.ExtractString(_kv); ok {
					data.Servers[i].Name = v
					consumed[keyPrefix+"servers.name"] = true
				}
			case "command":
				if raw, ok := cst.ExtractRaw(_kv); ok {
					if err := data.Servers[i].Command.UnmarshalTOML(raw); err != nil {
						return fmt.Errorf("command: %w", err)
					}
					consumed[keyPrefix+"servers.command"] = true
				}
			case "url":
				if v, ok := cst.ExtractString(_kv); ok {
					data.Servers[i].URL = v
					consumed[keyPrefix+"servers.url"] = true
				}
			case "headers-helper":
				if v, ok := cst.ExtractString(_kv); ok {
					data.Servers[i].HeadersHelper = &v
					consumed[keyPrefix+"servers.headers-helper"] = true
				}
			case "paginate":
				if v, ok := cst.ExtractBool(_kv); ok {
					data.Servers[i].Paginate = v
					consumed[keyPrefix+"servers.paginate"] = true
				}
			case "generate-resource-tools":
				if v, ok := cst.ExtractBool(_kv); ok {
					data.Servers[i].GenerateResourceTools = &v
					consumed[keyPrefix+"servers.generate-resource-tools"] = true
				}
			case "ephemeral":
				if v, ok := cst.ExtractBool(_kv); ok {
					data.Servers[i].Ephemeral = &v
					consumed[keyPrefix+"servers.ephemeral"] = true
				}
			case "progressive-disclosure":
				if v, ok := cst.ExtractBool(_kv); ok {
					data.Servers[i].ProgressiveDisclosure = &v
					consumed[keyPrefix+"servers.progressive-disclosure"] = true
				}
			case "nix-devshell":
				if v, ok := cst.ExtractString(_kv); ok {
					data.Servers[i].NixDevshell = &v
					consumed[keyPrefix+"servers.nix-devshell"] = true
				}
			}
		}
		{
			_pi := 0
			for _, _rc := range doc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers.headers" {
					data.Servers[i].Headers = cst.ExtractStringMap(_rc)
					consumed[keyPrefix+"servers.headers"] = true
					for _ik := range data.Servers[i].Headers {
						consumed[keyPrefix+"servers.headers"+"."+_ik] = true
					}
					break
				}
			}
		}
		{
			var _ftServersOauth *cst.Node
			_pi := 0
			for _, _rc := range doc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers.oauth" {
					_ftServersOauth = _rc
					break
				}
			}
			if _ftServersOauth != nil {
				consumed[keyPrefix+"servers.oauth"] = true
				oAuthVal := &OAuthConfig{}
				for _, _kv := range _ftServersOauth.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "client-id":
						if v, ok := cst.ExtractString(_kv); ok {
							oAuthVal.ClientID = v
							consumed[keyPrefix+"servers.oauth.client-id"] = true
						}
					case "callback-port":
						if v, ok := cst.ExtractInt(_kv); ok {
							oAuthVal.CallbackPort = v
							consumed[keyPrefix+"servers.oauth.callback-port"] = true
						}
					}
				}
				data.Servers[i].OAuth = oAuthVal
			} else {
				oAuthVal := &OAuthConfig{}
				_found := false
				for _, _kv := range _node.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "client-id":
						if v, ok := cst.ExtractString(_kv); ok {
							oAuthVal.ClientID = v
							_found = true
							consumed["client-id"] = true
						}
					case "callback-port":
						if v, ok := cst.ExtractInt(_kv); ok {
							oAuthVal.CallbackPort = v
							_found = true
							consumed["callback-port"] = true
						}
					}
				}
				if _found {
					data.Servers[i].OAuth = oAuthVal
				}
			}
		}
		{
			var _ftServersAnnotations *cst.Node
			_pi := 0
			for _, _rc := range doc.Root().Children {
				if _rc.Kind == cst.NodeArrayTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers" {
					if _pi > i {
						break
					}
					_pi++
					continue
				}
				if _pi == i+1 && _rc.Kind == cst.NodeTable && cst.TableHeaderKey(_rc) == keyPrefix+"servers.annotations" {
					_ftServersAnnotations = _rc
					break
				}
			}
			if _ftServersAnnotations != nil {
				consumed[keyPrefix+"servers.annotations"] = true
				annotationsVal := &AnnotationFilter{}
				for _, _kv := range _ftServersAnnotations.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "readOnlyHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.ReadOnlyHint = &v
							consumed[keyPrefix+"servers.annotations.readOnlyHint"] = true
						}
					case "destructiveHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.DestructiveHint = &v
							consumed[keyPrefix+"servers.annotations.destructiveHint"] = true
						}
					case "idempotentHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.IdempotentHint = &v
							consumed[keyPrefix+"servers.annotations.idempotentHint"] = true
						}
					case "openWorldHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.OpenWorldHint = &v
							consumed[keyPrefix+"servers.annotations.openWorldHint"] = true
						}
					}
				}
				data.Servers[i].Annotations = annotationsVal
			} else {
				annotationsVal := &AnnotationFilter{}
				_found := false
				for _, _kv := range _node.Children {
					if _kv.Kind != cst.NodeKeyValue {
						continue
					}
					switch cst.KeyValueName(_kv) {
					case "readOnlyHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.ReadOnlyHint = &v
							_found = true
							consumed["readOnlyHint"] = true
						}
					case "destructiveHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.DestructiveHint = &v
							_found = true
							consumed["destructiveHint"] = true
						}
					case "idempotentHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.IdempotentHint = &v
							_found = true
							consumed["idempotentHint"] = true
						}
					case "openWorldHint":
						if v, ok := cst.ExtractBool(_kv); ok {
							annotationsVal.OpenWorldHint = &v
							_found = true
							consumed["openWorldHint"] = true
						}
					}
				}
				if _found {
					data.Servers[i].Annotations = annotationsVal
				}
			}
		}
	}
	return nil
}
func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	if data.Ephemeral != nil {
		if err := cst.SetAny(container, "ephemeral", *data.Ephemeral); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ProgressiveDisclosure != nil {
		if err := cst.SetAny(container, "progressive-disclosure", *data.ProgressiveDisclosure); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.BuiltinNative != nil {
		if err := cst.SetAny(container, "builtin-native", *data.BuiltinNative); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.DisableMoxins) > 0 || cst.HasValue(container, "disable-moxins") {
			if err := cst.SetAny(container, "disable-moxins", data.DisableMoxins); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		_existPavedPaths := cst.FindArrayTableNodes(doc.Root(), "paved-paths")
		for i := range data.PavedPaths {
			var container *cst.Node
			if i < len(_existPavedPaths) {
				container = _existPavedPaths[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(doc.Root(), "paved-paths")
			}
			if data.PavedPaths[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.PavedPaths[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.PavedPaths[i].Description != "" || cst.HasValue(container, "description") {
				if err := cst.SetAny(container, "description", data.PavedPaths[i].Description); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				_existPavedPathsStages := cst.FindArrayTableNodes(doc.Root(), "paved-paths.stages")
				for i := range data.PavedPaths[i].Stages {
					var container *cst.Node
					if i < len(_existPavedPathsStages) {
						container = _existPavedPathsStages[i]
					} else {
						container = cst.AppendArrayTableEntryAfter(doc.Root(), "paved-paths.stages")
					}
					if data.PavedPaths[i].Stages[i].Label != "" || cst.HasValue(container, "label") {
						if err := cst.SetAny(container, "label", data.PavedPaths[i].Stages[i].Label); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
					{
						if len(data.PavedPaths[i].Stages[i].Tools) > 0 || cst.HasValue(container, "tools") {
							if err := cst.SetAny(container, "tools", data.PavedPaths[i].Stages[i].Tools); err != nil {
								return fmt.Errorf("%w", err)
							}
						}
					}
				}
			}
		}
	}
	if data.Credentials != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "credentials")
		if err := credentials.EncodeCommandConfigFrom(data.Credentials, doc, tableNode); err != nil {
			return fmt.Errorf("credentials: %w", err)
		}
	}
	{
		_existServers := cst.FindArrayTableNodes(doc.Root(), "servers")
		for i := range data.Servers {
			var container *cst.Node
			if i < len(_existServers) {
				container = _existServers[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(doc.Root(), "servers")
			}
			if data.Servers[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.Servers[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				v, err := data.Servers[i].Command.MarshalTOML()
				if err != nil {
					return fmt.Errorf("command: %w", err)
				}
				if err := cst.SetAny(container, "command", v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].URL != "" || cst.HasValue(container, "url") {
				if err := cst.SetAny(container, "url", data.Servers[i].URL); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if len(data.Servers[i].Headers) > 0 {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "headers")
				cst.DeleteAllValues(tableNode)
				for k, v := range data.Servers[i].Headers {
					if err := cst.SetAny(tableNode, k, v); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].HeadersHelper != nil {
				if err := cst.SetAny(container, "headers-helper", *data.Servers[i].HeadersHelper); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].OAuth != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "oauth")
				if data.Servers[i].OAuth.ClientID != "" || cst.HasValue(tableNode, "client-id") {
					if err := cst.SetAny(tableNode, "client-id", data.Servers[i].OAuth.ClientID); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].OAuth.CallbackPort != 0 || cst.HasValue(tableNode, "callback-port") {
					if err := cst.SetAny(tableNode, "callback-port", data.Servers[i].OAuth.CallbackPort); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].Annotations != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), container, "annotations")
				if data.Servers[i].Annotations.ReadOnlyHint != nil {
					if err := cst.SetAny(tableNode, "readOnlyHint", *data.Servers[i].Annotations.ReadOnlyHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.DestructiveHint != nil {
					if err := cst.SetAny(tableNode, "destructiveHint", *data.Servers[i].Annotations.DestructiveHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.IdempotentHint != nil {
					if err := cst.SetAny(tableNode, "idempotentHint", *data.Servers[i].Annotations.IdempotentHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Servers[i].Annotations.OpenWorldHint != nil {
					if err := cst.SetAny(tableNode, "openWorldHint", *data.Servers[i].Annotations.OpenWorldHint); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Servers[i].Paginate != false || cst.HasValue(container, "paginate") {
				if err := cst.SetAny(container, "paginate", data.Servers[i].Paginate); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].GenerateResourceTools != nil {
				if err := cst.SetAny(container, "generate-resource-tools", *data.Servers[i].GenerateResourceTools); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].Ephemeral != nil {
				if err := cst.SetAny(container, "ephemeral", *data.Servers[i].Ephemeral); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].ProgressiveDisclosure != nil {
				if err := cst.SetAny(container, "progressive-disclosure", *data.Servers[i].ProgressiveDisclosure); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Servers[i].NixDevshell != nil {
				if err := cst.SetAny(container, "nix-devshell", *data.Servers[i].NixDevshell); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	return nil
}
