schema = 3
result-type = "text"
substitute-result-uris = false
description = "Create a new issue"
command = "@BIN@/issue-create"
arg-order = ["repo", "title", "body", "labels"]

[input]
type = "object"
required = ["repo", "title"]

[input.properties.repo]
type = "string"
description = "Repository in OWNER/REPO format, or just REPO to default owner from the current repo's org"

[input.properties.title]
type = "string"
description = "Issue title"

[input.properties.body]
type = "string"
description = "Issue body"

[input.properties.labels]
type = "array"
description = "Labels to add"

[input.properties.labels.items]
type = "string"

[annotations]
open-world-hint = true
