schema = 3
substitute-result-uris = false
description = "Create a new pull request"
command = "@BIN@/pr-create"
arg-order = ["repo", "title", "body", "base", "head", "draft", "labels"]

[input]
type = "object"
required = ["repo", "title"]

[input.properties.repo]
type = "string"
description = "Repository in OWNER/REPO format, or just REPO to default owner from the current repo's org"

[input.properties.title]
type = "string"
description = "Pull request title"

[input.properties.body]
type = "string"
description = "Pull request body"

[input.properties.base]
type = "string"
description = "Base branch (the branch into which you want your code merged)"

[input.properties.head]
type = "string"
description = "Head branch (the branch that contains commits for your pull request). Usually necessary because gh refuses to create PRs when the working tree has untracked files unless --head is explicit. Format: OWNER:BRANCH for cross-repo PRs"

[input.properties.draft]
type = "boolean"
description = "Create as draft pull request"

[input.properties.labels]
type = "array"
description = "Labels to add"

[input.properties.labels.items]
type = "string"

[annotations]
open-world-hint = true
